# Setup
title:        Mypower
description:  Cayman is a clean, responsive theme for GitHub Pages.
tagline:      A responsive theme for your project on GitHub Pages
baseurl:      ""
paginate:     1
locale:       "en"

show_downloads: true
google_analytics:


theme: jekyll-theme-cayman

